### ISSUE TITLE
Trailing ?> in template/clerk/tracking.phtml

### ISSUE THREAD

**Issue by plasticid** [clerkio/clerk-magento#15]
Line 8 of app/design/frontend/base/default/template/clerk/tracking.phtml has an extra closing ?>

**Comment by brunsgaard** [comment]
Thank you, I will look into it tomorrow ;)

**Comment by brunsgaard** [comment]
https://github.com/clerkio/clerk-magento/blob/master/design/template/tracking.phtml#L7

line 7 is commented out, so the there is no extra `?>`, you see?

**Comment by plasticid** [comment]
The // doesn't comment out the ?>  so there is a an extra ?> shown in the html.... /* */ would work though

**Comment by brunsgaard** [comment]
Okay, I will never be good friends with PHP, I will fix it ;) Thanks again.

**Comment by brunsgaard** [comment]
There you go, it will go into next release
