### ISSUE TITLE
Add clerk/magento to packagist.org

### ISSUE THREAD

**Issue by giuseppemorelli** [clerkio/clerk-magento#48]
Hi guys,
please can you add your repository to packagist.org like magento2 extension?
I know composer for magento1 is less used but for me is very helpful.

Thank you for your support!

**Comment by RBech** [comment]
Hi @giuseppemorelli

Sorry for the delay, it's added now https://packagist.org/packages/clerk/magento :)

**Comment by giuseppemorelli** [comment]
Thanks @RBech!
