### ISSUE TITLE
Module needs an actual User Agent name

### ISSUE THREAD

**Issue by olzen90** [clerkio/clerk-magento#49]
Problem
-------
Magento module uses generic Python User Agent name. Some developers want to block out unnecessary traffic, but its hard to give the module access, without a more defined name.

Reproduce
------
The following call is being sent by the module:

_52.28.255.187 - - [10/Oct/2016:11:14:47 +0200] "GET /clerk/api/product/?limit=200&page=1&store=4 HTTP/1.1" 401 188 "-" "__python-requests/2.7.0 CPython/2.7.10 Linux/4.1.13-19.31.amzn1.x86_64__"_

Expected
-----
Module should use a more clearly defined User Agent Name, like __clerk_bot__, allowing developers to easily allow access for our module only.

Example:
_52.28.255.187 - - [10/Oct/2016:11:14:47 +0200] "GET /clerk/api/product/?limit=200&page=1&store=4 HTTP/1.1" 401 188 "-" "____clerk_bot____"_

**Comment by RBech** [comment]
This issue is not related to the magento extension but to the internal workings of the clerk.io system, relay to HKB ;)
