### ISSUE TITLE
Error parsing body - doesn't seem to be a chunked message

### ISSUE THREAD

**Issue by wclbrijesh** [clerkio/clerk-magento#54]
Hi,

I am getting this error after installing clerk (3.3.0) module on my magento(1.7.0).

Error is showing given below.

*******************************************************************************************************************

Error parsing body - doesn't seem to be a chunked message

Trace:
#0 /var/www/html/lib/Zend/Http/Response.php(262): Zend_Http_Response::decodeChunkedBody('??????????E?=??...')
#1 /var/www/html/app/code/community/Clerk/Clerk/Model/System/Config/Source/FacetAttributes.php(37): Zend_Http_Response->getBody()
#2 /var/www/html/app/code/community/Clerk/Clerk/Model/System/Config/Source/FacetAttributes.php(12): Clerk_Clerk_Model_System_Config_Source_FacetAttributes->getFacetAttributes()
#3 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(463): Clerk_Clerk_Model_System_Config_Source_FacetAttributes->toOptionArray(true)
#4 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(229): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#5 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(164): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#6 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(92): Mage_Adminhtml_Block_System_Config_Form->initForm()
#7 /var/www/html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#8 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Adminhtml_System_ConfigController->editAction()
#9 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#10 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/www/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/www/html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#13 /var/www/html/index.php(91): Mage::run('', 'store')
#14 {main}
#14 {main}

****************************************************************************************************************
Please check this and let me know that how can we fixed this issue.

Thanks,
Brijesh

**Comment by RBech** [comment]
Hi :) This is an error with Magento 1.7.0, as outlined here https://magento.stackexchange.com/questions/17772/dhl-is-not-working-with-production-api-url the fix is to either update magento or to grab the file lib/Varien/Http/Adapter/Curl.php from magento 1.8.1
