### ISSUE TITLE
decoding chunked messages too many times

### ISSUE THREAD

**Issue by mmmols** [clerkio/clerk-magento#55]
Any specific you are using Varien_Http_Client rather than Zend_Http_Client:

https://github.com/clerkio/clerk-magento/blob/07f3928f353480f4c770596986649ea24880f7f1/code/Model/Communicator.php#L184

Varien_Http_Client does not take into account that cURL decodes chunked messages, so when Varien_Http_Client decodes it, it messes up the transmission's chunk sizes. 

I found this issue while updating Clerk following this: https://help.clerk.io/using-clerk-io-on-magento-1/upgrading-extension/upgrading-the-clerkio-magento-1-extension-from-v1

When using Varien_Http_Client I get this error:

```
There has been an error processing your request
Error parsing body - doesn't seem to be a chunked message

Trace:
#0 /var/www/magento/lib/Zend/Http/Response.php(262): Zend_Http_Response::decodeChunkedBody('\x1F\x8B\x08\x00\x00\x00\x00\x00\x00\x035\x8E\xB9\x0E\xC2...')
#1 /var/www/magento/app/code/community/Clerk/Clerk/Block/Adminhtml/System/Config/Form/FacetedSearchFieldset.php(56): Zend_Http_Response->getBody()
#2 /var/www/magento/app/code/community/Clerk/Clerk/Block/Adminhtml/System/Config/Form/FacetedSearchFieldset.php(17): Clerk_Clerk_Block_Adminhtml_System_Config_Form_FacetedSearchFieldset->keysValid()
#3 /var/www/magento/lib/Varien/Data/Form/Element/Abstract.php(223): Clerk_Clerk_Block_Adminhtml_System_Config_Form_FacetedSearchFieldset->render(Object(Varien_Data_Form_Element_Fieldset))
```

My solution is to use Zend_Http_Client rather than Varien_Http_Client. This fixes the issue.

This is tested in Magento 1.7.

**Comment by RBech** [comment]
No reason in particular no, will switch to zend_http_client next release
