### ISSUE TITLE
Source model class name wrong

### ISSUE THREAD

**Issue by nguynhanam** [clerkio/clerk-magento#90]
In the latest version (4.5.3) 
`app/code/community/Clerk/Clerk/etc/system.xml:91`
You are using source model: clerk/system_config_source_productvisibility and it name is not correct. We should replace source model name or class name Clerk_Clerk_Model_System_Config_Source_ProductVisibility

**Comment by mebbopakko** [comment]
Thank you, that was a lifesaver 👍

**Comment by Drugantibus** [comment]
Hi @nguynhanam, thanks for the issue! A fix has just been pushed, and it will be included in the next release.

Closing this for now, please let us know if there are any further issues.
